### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by mc436572** [wzx140/wx_robo#1]
2020-10-14 00:04:48,664 - root - INFO - 登录成功
2020-10-14 00:04:49,026 - root - ERROR -  #######################规则改变
Traceback (most recent call last):
  File "run.py", line 27, in main
    get_user_info(url)
  File "D:\03_PyProject\wxRobat\wx.py", line 126, in get_user_info
    raise RuntimeError(url + ' 规则改变')
RuntimeError: ############################################ 规则改变

网页版现在不灵了， 还有办法？

**Comment by wzx140** [comment]
@mc436572 刚刚提交了新代码，我测试后已经可以接受和发送消息 

如果遇到异常，尝试在微信上退出web登陆并重新运行程序
